install: true
script: true
before_deploy:
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
deploy:
  provider: script
  script: rsync --quiet cronjob.js index.html $PRODUCTION_USER@$PRODUCTION_HOST:$PRODUCTION_WEBROOT
  on:
    branch: master
